/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Ajuda;

import br.com.telaInicial.JFrameTelaInicial;

/**
 *
 * @author Jilcimar Fernandes
 */
public class JFrameTelaAjuda extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTelaAjuda
     */
    public JFrameTelaAjuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagemBarcos = new javax.swing.JLabel();
        labelImagemSubmarino = new javax.swing.JLabel();
        labelImagemBomba = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(701, 596));
        setResizable(false);
        getContentPane().setLayout(null);

        labelImagemBarcos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Ajuda/barcoexemplo2Partes.png"))); // NOI18N
        getContentPane().add(labelImagemBarcos);
        labelImagemBarcos.setBounds(50, 130, 110, 60);

        labelImagemSubmarino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Ajuda/submarinoexemplo.png"))); // NOI18N
        getContentPane().add(labelImagemSubmarino);
        labelImagemSubmarino.setBounds(60, 220, 90, 50);

        labelImagemBomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Ajuda/bombaexemplo.png"))); // NOI18N
        getContentPane().add(labelImagemBomba);
        labelImagemBomba.setBounds(50, 290, 70, 60);

        botaoVoltar.setFont(new java.awt.Font("Metal Lord", 0, 12)); // NOI18N
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Ajuda/voltar.png"))); // NOI18N
        botaoVoltar.setText("voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar);
        botaoVoltar.setBounds(480, 510, 120, 50);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("QUANTIDADE DE EMBARÇÕES:\n\n6 BARCOS:\n\n\n\n\n10 SUBMARINOS:\n\n\n\n\nBOMBAS:\n\n\n\n\nREGRAS DO JOGO\n\nHá um tabuleiro de 10x10, ou seja, 100 blocos. \nHá 10 submarinos escondidos (um em cada bloco) e \n6 barcos compostos de 2 partes cada.\nO objetivo do jogo é descobrir onde estão essas\nembarcações e acertá-las.\nA cada tiro na água o jogador perde 1 vida. \nO jogo só acaba quando você descobrir 5 embarcações \nou quando suas vidas na partida acabam.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 70, 570, 500);

        jLabel1.setFont(new java.awt.Font("Metal Lord", 0, 48)); // NOI18N
        jLabel1.setText("ajuda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 131, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
          this.dispose();
        JFrameTelaInicial volta = new JFrameTelaInicial();
        volta.show();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaAjuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelImagemBarcos;
    private javax.swing.JLabel labelImagemBomba;
    private javax.swing.JLabel labelImagemSubmarino;
    // End of variables declaration//GEN-END:variables
}
